trigger:
  branches:
    include:
      - "*"
  paths:
    include:
      - '/golang-build-base'

pool:
  vmImage: 'ubuntu-latest'

variables:
  DOCKER_TAG_GENERATORT_SCRIPT: '$(system.defaultWorkingDirectory)/scripts/generate-docker-tag.sh'
  DOCKER_CONTAINER_REGISTRY: 'Decentralized Cloud Docker Hub'
  DOCKER_REPOSITORY_NAME: 'decentralizedcloud/golang-build-base'
  DOCKER_FILE_PATH: '$(system.defaultWorkingDirectory)/golang-build-base/Dockerfile'

steps:
- task: Bash@3
  inputs:
    filePath: $(DOCKER_TAG_GENERATORT_SCRIPT)
    arguments: $(Build.SourceBranch) $(Build.BuildId)
  displayName: "Generating docker tags"

- task: Docker@2
  displayName: Docker Login
  inputs:
    containerRegistry: $(DOCKER_CONTAINER_REGISTRY)
    command: 'login'

- task: Docker@2
  displayName: Building Golang Build Base Docker Image
  inputs:
    containerRegistry: $(DOCKER_CONTAINER_REGISTRY)
    repository: $(DOCKER_REPOSITORY_NAME)
    command: 'buildAndPush'
    Dockerfile: $(DOCKER_FILE_PATH)
    tags: |
      $(GENERATED_DOCKER_TAG_ID)
      $(GENERATED_DOCKER_TAG)

- task: Docker@2
  displayName: Docker Logout
  inputs:
    containerRegistry: $(DOCKER_CONTAINER_REGISTRY)
    command: 'logout'
