trigger:
- master
- feature/*
- bug/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: docker build -f Dockerfile .
  workingDirectory: '$(system.defaultWorkingDirectory)/go-build'
  displayName: 'Building Golang docker build base image'
