trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - master
      - release/*
      - feature/*
      - bug/*
  paths:
    exclude:
      - README.md

pool:
  vmImage: 'ubuntu-latest'

variables:
  DOCKER_CONTAINER_REGISTRY: 'Decentralized Cloud Docker Hub'
  PROTOBUF_BUILDER_DOCKER_REPOSITORY_NAME: 'decentralizedcloud/protobuf-builder'
  K8S_TOOLSET_DOCKER_REPOSITORY_NAME: 'decentralizedcloud/k8s-toolset'

steps:
- task: Bash@3
  displayName: "Generating docker tags"
  inputs:
    filePath:  '$(system.defaultWorkingDirectory)/script/generate-version.sh'
    arguments: $(Build.SourceBranch)

- task: Docker@2
  displayName: Build Protobuf builder image
  inputs:
    repository: $(PROTOBUF_BUILDER_DOCKER_REPOSITORY_NAME)
    command: 'build'
    Dockerfile: '$(system.defaultWorkingDirectory)/protobuf-builder/Dockerfile'
    buildContext: '$(system.defaultWorkingDirectory)'
    arguments: '--build-arg VERSION=$(VERSION)'
    tags: $(VERSION)

- task: Docker@2
  displayName: Build K8S toolset image
  inputs:
    repository: $(K8S_TOOLSET_DOCKER_REPOSITORY_NAME)
    command: 'build'
    Dockerfile: '$(system.defaultWorkingDirectory)/k8s-toolset/Dockerfile'
    buildContext: '$(system.defaultWorkingDirectory)'
    arguments: '--build-arg VERSION=$(VERSION)'
    tags: $(VERSION)

- task: Docker@2
  displayName: Docker Login
  inputs:
    containerRegistry: $(DOCKER_CONTAINER_REGISTRY)
    command: 'login'

- task: Docker@2
  displayName: Push Protobuf builder image
  inputs:
    containerRegistry: $(DOCKER_CONTAINER_REGISTRY)
    repository: $(PROTOBUF_BUILDER_DOCKER_REPOSITORY_NAME)
    command: 'push'
    buildContext: '$(system.defaultWorkingDirectory)'
    tags: $(VERSION)

- task: Docker@2
  displayName: Push K8S toolset image
  inputs:
    containerRegistry: $(DOCKER_CONTAINER_REGISTRY)
    repository: $(K8S_TOOLSET_DOCKER_REPOSITORY_NAME)
    command: 'push'
    buildContext: '$(system.defaultWorkingDirectory)'
    tags: $(VERSION)

- task: Docker@2
  displayName: Docker Logout
  inputs:
    containerRegistry: $(DOCKER_CONTAINER_REGISTRY)
    command: 'logout'

